vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        hall_images:
            uri_prefix: /images/hall
            upload_destination: '%kernel.project_dir%/public/images/hall'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
